/* Definitions of code flow time stamp monitoring points */

#ifndef __CFLOW_TSTAMP_USER_H__
#define __CFLOW_TSTAMP_USER_H__

#define CFLOW_TSTAMP_USER_PACKET_RX		0
#define CFLOW_TSTAMP_USER_PACKET_PARSED	1
#define CFLOW_TSTAMP_USER_FLOWCACHE_MISS	2
#define CFLOW_TSTAMP_USER_FLOWCACHE_HIT	3
#define CFLOW_TSTAMP_USER_INGRESS_UNCACHED	4
#define CFLOW_TSTAMP_USER_INGRESS_CACHED	5
/* unused - 6 */
#define CFLOW_TSTAMP_USER_EGRESS_UNCACHED	7
#define CFLOW_TSTAMP_USER_EGRESS_CACHED	8
#define CFLOW_TSTAMP_USER_CHECKSUMS		9
#define CFLOW_TSTAMP_USER_AFTER_DEPARSING	10
/* unused - 11 */
/* unused - 12 */

/* exit nodes */
#define CFLOW_TSTAMP_USER_DROP_ON_INGRESS 	13
#define CFLOW_TSTAMP_USER_DROP_ON_EGRESS  	14
#define CFLOW_TSTAMP_USER_TRANSMIT_PACKET 	15

#endif /* __CFLOW_TSTAMP_USER__*/

