/* Copyright (C) 2015,  Netronome Systems, Inc.  All rights reserved. */

#ifndef __PIF_PARSE_ERRORS_H__
#define __PIF_PARSE_ERRORS_H__

enum {
    PIF_PARSE_ERROR_SUCCESS = 0,
    PIF_PARSE_ERROR_INDEX_OUT_OF_BOUNDS,
    PIF_PARSE_ERROR_OUT_OF_PACKET,
    PIF_PARSE_ERROR_HEADER_TOO_LONG,
    PIF_PARSE_ERROR_HEADER_TOO_SHORT,
    PIF_PARSE_ERROR_UNHANDLED_SELECT,
    PIF_PARSE_ERROR_CHECKSUM,
    PIF_PARSE_ERROR_CUSTOM,
    PIF_PARSE_ERROR_LAST,
    PIF_PARSE_ERROR_MAX = 64,
};

/* Custom parser error are declared from PIF_PARSE_ERROR_LAST+ */
#define PIF_PARSE_ERROR_CUSTOM_ENCODE(x) \
    (PIF_PARSE_ERROR_LAST + (x) >= PIF_PARSE_ERROR_MAX ? \
        PIF_PARSE_ERROR_CUSTOM : PIF_PARSE_ERROR_LAST + (x))
#define PIF_PARSE_ERROR_CUSTOM_DECODE(x) ((x) - PIF_PARSE_ERROR_LAST)
#define PIF_PARSE_ERROR_IS_CUSTOM(x) ( (x) >= PIF_PARSE_ERROR_CUSTOM)

enum {
    PIF_DEPARSE_ERROR_SUCCESS = 0,
    PIF_DEPARSE_ERROR_BUFFER_OVERRUN,
    PIF_DEPARSE_ERROR_HEADER_TOO_LONG,
    PIF_DEPARSE_ERROR_HEADER_TOO_SHORT,
    PIF_DEPARSE_ERROR_OFFSET_TOO_LARGE,
    PIF_DEPARSE_ERROR_LAST,
};

#endif /* __PIF_PARSE_ERRORS_H__ */
